name: ne-klub-bot

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker build
        run: docker build -t ne-klub-bot:0.0.1 .
      - name: Tag docker container
        run: docker tag ne-klub-bot:0.0.1 5dt1yim57hnf1ap/ne-klub-bot:0.0.1
      - name: Push docker container to registry
        run: docker push 5dt1yim57hnf1ap/ne-klub-bot:0.0.1
