name: ne-klub-bot

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: docker build -t ne-klub-bot .
